# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Get Campaign Data

on:
  workflow_dispatch:
    inputs:
      clubId:
        type: string
        description: Club ID (Can be found in tm.io)
        required: true
        default: "2270"
      campaignId:
        type: string
        description: Campaign ID (Can be found in tm.io)
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.2]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: node process_campaign.js
        env:
          CLUB_ID: ${{ inputs.clubId }}
          CAMPAIGN_ID: ${{ inputs.campaignId }}
      - name: Save output file
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            output.json
